### ISSUE TITLE
any update on beryllium touch support?

### ISSUE THREAD

**Issue by salam-siddique** [edk2-porting/WOA-Drivers#13]

**Comment by TAOcroatia** [comment]
Still nothing

**Comment by salam-siddique** [comment]
how do i install a normal x64 application?

**Comment by salam-siddique** [comment]
i have been trying but to no success, its just 200mb drafting software to open drawings

**Comment by salam-siddique** [comment]
could anyone please help

**Comment by TAOcroatia** [comment]
Ask in discord or telegram, this is not the place to ask
