### ISSUE TITLE
One plus 6T non original screen cannot be touched

### ISSUE THREAD

**Issue by doubijunNB** [edk2-porting/WOA-Drivers#16]
As the title goes, although it is made of LCD, the touch chip is the same as the original

**Comment by xqymain** [comment]
I have the same problem, is there any progress now？

**Comment by TheMorc** [comment]
@xqymain
> I have the same problem, is there any progress now？

Try the latest driver from WOA-Drivers, it should work now on your replaced screen with a counterfeit digitizer controller IC.

**Comment by TheMorc** [comment]
I guess this specific issue can be closed because touch works now for @doubijunNB and alsp possibly for @xqymain even though he hasn't reported any updates.
