### ISSUE TITLE
Oneplus 6 showing black screen during installation

### ISSUE THREAD

**Issue by leohearts** [edk2-porting/WOA-Drivers#17]
Time: 2021-09-03/12:00 UTC+8
Newest sources
after dism++ deploy, reboot, it installed like normal, but after an automate reboot during installation it just showed a black screen with LED on.
~~It may be caused by some changes after https://github.com/edk2-porting/WOA-Drivers/tree/0492fccf7a38d3a3d628e695c5144fb881e9d220 (8 days ago), this version works for me.~~

[UPDATE] It seems that this problem comes from ~~Sybsystems/MCFG_Subsys_ext or~~ subsystems/ssdd .
The real difference is my previous setup got these two folders missing for some reason. After deleting these two folders it booted up again (with some drivers missing, such as wifi and audio.)
After re-adding subsystem/ssdd to system, it stops start on user login screen.
Installing Sybsystems/MCFG_Subsys_ext is OK.
I have to boot into PE and delete subsystem/ssdd driver, and it started again.

**Comment by leohearts** [comment]
Yes it works!
I replaced SSDD/wlanmdsp.mbn with the one extracted from stock modem_a image, and installed it.
WiFi now works (but audio and power management doesn't, as before. )

[wlanmdsp.mbn.zip](https://github.com/edk2-porting/WOA-Drivers/files/7106539/wlanmdsp.mbn.zip)

**Comment by strongtz** [comment]
Does the problem still occur with latest drivers and UEFI?

**Comment by leohearts** [comment]
> Does the problem still occur with latest drivers and UEFI?

Yes.
After some time during installation it turned off
![IMG_20210922_165521.jpg](https://user-images.githubusercontent.com/24632029/134313759-469babe7-e6ea-4567-a8c0-0a91b80e67cc.jpg)

**Comment by Jbrimbelibap** [comment]
I have this same issue, using your wlanmdsp.mbn didn't fix it for me. Should i just try to remove drivers , starting with subsystems/ssdd?

**Comment by Jbrimbelibap** [comment]
If it can help anyone, here the wlanmdsp.mbn from my modem_a image
[wlanmdsp.zip](https://github.com/edk2-porting/WOA-Drivers/files/8192923/wlanmdsp.zip)

**Comment by leohearts** [comment]
> I have this same issue, using your wlanmdsp.mbn didn't fix it for me. Should i just try to remove drivers , starting with subsystems/ssdd?

Try using the driver from your modem partition?
Sorry I don't exactly know how can I help you…

**Comment by Jbrimbelibap** [comment]
Yeah i'm doing this right now, we'll see. If you don't mind uploading your old firware folder with everything working it would be very useful, maybe new versions of the firmware broke more stuff for the chinese version of the phone

**Comment by Jbrimbelibap** [comment]
![PXL_20220306_192859438](https://user-images.githubusercontent.com/90109439/156936880-692e465b-770b-4386-a298-ec6497417782.jpg)
Using sdm845 generic drivers gets me much further

**Comment by leohearts** [comment]
Resolved. It turned out to be the matter of my outdated firmware :(
(I left it with Android 8 for debugging purpose)
