### ISSUE TITLE
Belleryum touchscreen error 12

### ISSUE THREAD

**Issue by Tonio1987fr** [edk2-porting/WOA-Drivers#21]
Hello 
I have error 12 for the touchscreen on my pocophone F1
It's last driver and uefi boot and new windows install
Do you have idea why ?
![image](https://user-images.githubusercontent.com/21991246/133246456-524ac407-d041-4548-b279-669e3ffbb612.png)

Thanks

**Comment by TheMorc** [comment]
You also need to download this [devcfg partition](https://cdn.discordapp.com/attachments/736563712466616391/880541358178320454/devcfg.img) and flash it using `fastboot flash devcfg_ab devcfg.img`

**Comment by Tonio1987fr** [comment]
I have flash the img file and reinstalled the windows and drivers. I still have the same error.

**Comment by TheMorc** [comment]
@Tonio1987fr and do you actually have a FocalTech digitizer on your phone?

**Comment by Tonio1987fr** [comment]
How can I see it? i deleted android.
The driver is automatically used, but does not work.

**Comment by curoviyxru** [comment]
I confirm that too. My phone has EBBG/FTS panel and I have flashed devcfg image, but it shows error 12.
