### ISSUE TITLE
BSOD after install latest drivers

### ISSUE THREAD

**Issue by ZH-XiJun** [edk2-porting/WOA-Drivers#31]
When I install the latest  driver in WinPE, win11 ran into  BSOD and return an error code "DRIVER_PNP_WATCHDOG" after rebooting.
I tried redeploy win11, but it doesn't work. The old-version drivers can boot normally, but I want touchscreen! 
How to fix this problem?

**Comment by strongtz** [comment]
@ZH-XiJun You need to flash devcfg. Check https://renegade-project.org/#/en/windows/state-frame.html
