### ISSUE TITLE
米8UD，win11系统下无法正常关机、重启。

### ISSUE THREAD

**Issue by XingLplus** [edk2-porting/WOA-Drivers#34]
米8UD版本，win11系统下无法正常关机、重启。一旦重启或者关机，机器会处于黑屏状态但是屏幕是亮的系统并没有正常的关闭。
自动进入锁屏模式也会出现此情况。希望解决一下。米8UD刷UD的引导文件和驱动触摸无法正常使用，没有电话卡选项。
下载地址[https://download.renegade-project.cn/](url)
但是使用米8的引导和驱动都能够正常使用但是关机重启还是没有解决。

**Comment by strongtz** [comment]
多等一会就会正常关机或重启，该问题无法修复
