### ISSUE TITLE
Connection error with bluetooth device (Beryllium) 

### ISSUE THREAD

**Issue by HeroRickyGAMES** [edk2-porting/WOA-Drivers#35]
I went to connect a bluetooth headset and for some reason it showed me blue screen.
My ps4 controller connected smoothly, but my headphones and my speaker didn't work.
The phone is from the KD913 model, I have a KD910 but it has a problem and will possibly cause the same blue screen.

**Comment by TAOcroatia** [comment]
Uninstall audio drivers
