### ISSUE TITLE
GPU Drivers are missing

### ISSUE THREAD

**Issue by 10-p** [edk2-porting/WOA-Drivers#4]
Hey there! 

Looking at some tutorial and youtube videos it seems that drivers for achieving 3d acceleration are available for OnePlus devices yet they're not in this repository.

Is there a repo with these? When are you planning to release those here otherwise?

Awesome work though!

**Comment by TheMorc** [comment]
@10-p the GPU has to be supported in Renegade first

**Comment by BigfootACA** [comment]
it is now supported and the driver has been uploaded
