### ISSUE TITLE
小米8 安装最新的版本后，启动直接蓝屏，提示需要修复？ 怎么处理

### ISSUE THREAD

**Issue by cander0815** [edk2-porting/WOA-Drivers#46]
如图：
![](https://user-images.githubusercontent.com/23468736/160644443-fa88bc13-4320-456f-a45f-2be7f86d40ce.jpeg)

**Comment by Aro2142** [comment]
Try installing Windows 11 arm build 22547 and earlier, or install Windows 10 arm

**Comment by lujimmy** [comment]
首先，确认是否关闭了驱动签名。然后，连接键盘，按提示点击 Windows键检查UEFI设置。最后，重新安装吧。
