### ISSUE TITLE
mi8(dipper) sim can not work after fastboot flash devcfg with devcfg-dipper_FixTS.img

### ISSUE THREAD

**Issue by lujimmy** [edk2-porting/WOA-Drivers#51]
mi8(dipper) tounch screen work well with the v1.1.1 after  fastboot flash devcfg with devcfg-dipper_FixTS.img, but the sims can not work neither in windows arm nor miui

**Comment by ShallowAi** [comment]
To use LTE at windows, you should install  correct driver and not damaged backup QCN partition.

And remember do not change sim slot in both windows and card slot, it will damage your QCN partition.

If u can't connect to network.
Try reflash qcn partition and install driver again.
