### ISSUE TITLE
oneplus6T mobile charging problem

### ISSUE THREAD

**Issue by onlinerender** [edk2-porting/WOA-Drivers#59]
any one have this problem oneplus6T mobile charging problem in windows 11 arm.
android charging fine.. any one please help me solution
latest versions using (v2.0rc2))

**Comment by sehzam** [comment]
hey man
i had the same issue.
the clou is you need min. 3A USB C TO USB C CABLE
and ancharger with min 2A USB C output.

or the xiaomi mi turbo(USB A TO USB C) (ORANGE COLOR PLUG) charge cable works fine with regular charger like 2A.
on amazon for 15bucks

**Comment by strongtz** [comment]
Please use the latest edk2-sdm845 release with a PD-compatible charger
