### ISSUE TITLE
ADB fastboot are not working 

### ISSUE THREAD

**Issue by TripleA374** [edk2-porting/WOA-Drivers#62]
ADB fastboot interface not detected driver please solve

**Comment by Idonotkno** [comment]
@TripleA374 ？？No one understands what you mean.

**Comment by Idonotkno** [comment]
@TripleA374 Still not understood.

**Comment by TripleA374** [comment]
Are you developer?

**Comment by Idonotkno** [comment]
@TripleA374 No one understands what you are talking about, because your problem is sent by GitHub robots to everyone in the group. If you are talking about the ADB/FASTBOOT driver that you can not be available under WOA, then go to see the SC8180X driver, inside itThere is a ADB driver. If you say that your device cannot be connected in FastBoot, it is your own problem.

**Comment by TripleA374** [comment]
Sorry 😔 you say I understand my poco F1 devices is connected devices but ADB fastboot not detected I trying manual driver not install windows 10/11 so I understand have the problem poco driver

**Comment by sc-ah** [comment]
> Sorry 😔 you say I understand my poco F1 devices is connected devices but ADB fastboot not detected I trying manual driver not install windows 10/11 so I understand have the problem poco driver

can you maybe try to use translator i think there is a huge language barrier

**Comment by TripleA374** [comment]
Wicth driver change? any driver not working windows 10/11 I don't understand this on windows arm problem or driver

**Comment by TripleA374** [comment]
Wicth driver change? any driver not working windows 10/11 I don't understand this on windows arm problem or driver

**Comment by Idonotkno** [comment]
@TripleA374 If you need a windows arm driver, look at the 8180 driver in edk2-porting, which has an ADB driver. You didn't explain your problem from the beginning.

**Comment by TripleA374** [comment]
Can this on driver working my poco F1 beryllium

**Comment by TripleA374** [comment]
I don't find 8081 driver
