### ISSUE TITLE
尊敬的开发者们能关注一下Mix2的驱动吗（msm8998）（谢谢！）

### ISSUE THREAD

**Issue by RoyanCpp** [edk2-porting/WOA-Drivers#63]
费劲力气给一台mix2装上的windows结果没有驱动，真滴难受啊

**Comment by RoyanGG953** [comment]
> 实时上是有的，只是没有列出

能在哪里下载或看到吗

**Comment by qaz6750** [comment]
![屏幕截图 2022-07-14 083347](https://user-images.githubusercontent.com/66907230/178859840-8be79ea4-1094-47df-ac58-99500ce83135.jpg)
![屏幕截图 2022-07-14 083405](https://user-images.githubusercontent.com/66907230/178859844-a3c21bb1-fb1d-422e-a522-bc9d3eb28ffd.jpg)

**Comment by RoyanGG953** [comment]
> 实际上因为mix2的usb和pep相互冲突，你只能选择保留其中一个

驱动需要额外修改acpi吗，大概能支持那些驱动？

**Comment by degdag** [comment]
Acpi still need a hug changes to be adapted for mi mix2 . at last if you want touchscreen than you need to make the same modifications as been Donne for Mi 6 since they use the same touch ic

**Comment by 1208079702** [comment]
> > 实际上因为mix2的usb和pep相互冲突，你只能选择保留其中一个
> 
> 驱动需要额外修改acpi吗，大概能支持那些驱动？

有后续嘛？我用的mindows 安装的 请问怎么安装pep驱动呢

**Comment by zzxxxxxzxxxz** [comment]
你可以直接套用小米6除了usb之外的所有驱动(包括boot镜像)，pep,触摸屏,蓝牙都可用,GPU无法启用。

_Moderation Edit - Machine Translation:_ You can directly apply all drivers (including boot image) of Xiaomi 6 except USB. PEP, touch screen, and Bluetooth are all available, but GPU cannot be enabled.

**Comment by zzxxxxxzxxxz** [comment]
不过你可能需要修改一下boot和触摸屏有关的驱动，小米6的显示屏是1920x1080的，而mix2是2160x1080,这可能会导致显示不全或触摸错误。

_Moderation Edit - Machine Translation:_ However, you may need to modify the boot and touch screen related drivers. The display of Xiaomi 6 is 1920x1080, while that of Mix2 is 2160x1080, which may cause incomplete display or touch errors.
