### ISSUE TITLE
Xiaomi Mi 8 Touchscreen driver stops working

### ISSUE THREAD

**Issue by Neo802** [edk2-porting/WOA-Drivers#73]
Hello there.
I have installed Windows 11 ARM64 on Xiaomi Mi 8 using Project Renegade, flashed the devcfg image into devcfg_a and disabled the power saving features on the Touchscreen driver. It worked fine on most apps and such, however, after a while, it stops working. I have tried multiple times to re-enable touchscreen, either by disabling the touchscreen driver and reenabling it, restarting the phone and so on, however, the touchscreen still remains undetected.

**Comment by GiaSen** [comment]
I suggest you to reflash stock devcfg with `fastboot flash devcfg_ab devcfg.img` (you can grab the img from any firmware zip or ROM like my PixelExperience 12.1)
then flash custom one again with same command, yes partition is detected as devcfg_ab

**Comment by Neo802** [comment]
Windows apparently is now stuck in a bootloop after flashing the devcfg from Pixel Experience and then the Windows one with the same command.

**Comment by GiaSen** [comment]
Oh that happened to me as well when touch wasn't working (from installation) when I flashed in devcfg_a and tried what I said, I had no idea how to fix so I went back to android and reinstall from zero

**Comment by Neo802** [comment]
I restarted the phone and now not only does the Windows work fine, but the touchscreen does as well. Thank you.

**Comment by GiaSen** [comment]
great

**Comment by Neo802** [comment]
Update: Touchscreen again stopped working

**Comment by strongtz** [comment]
duplicate with https://github.com/edk2-porting/WOA-Drivers/issues/56
