### ISSUE TITLE
Beryllium: Cannot boot into Win10

### ISSUE THREAD

**Issue by RusJJ** [edk2-porting/WOA-Drivers#8]
Hi there! Installed the latest **MINIMUM** driver. Experiencing crash "IRQL LESS OR EQUAL".
**WITHOUT** drivers is bootable but OTG IS **NOT WORKING**.

WoA version: 19043.1023.210517-1726.VB_RELEASE_SVC_PROD3_CLIENTCORE_OEMRET_A64FRE

**Comment by RusJJ** [comment]
Btw with all shipped drivers OS is completely freezes at loading screen (with 5 white circles) and Phone is rebooting

**Comment by RusJJ** [comment]
Okay, it looks like that Windows version is kinda outdated. Got the latest ISO image: now im able to boot. But there's a problem: i cannot boot into a setup window, infinitely loading

**Comment by Idonotkno** [comment]
@RusJJ Please take a look at the tutorial. The use of Windows Installer on our device may cause the device to become brick, so it needs to be installed manually by dism/dism++

**Comment by RusJJ** [comment]
> @RusJJ Please take a look at the tutorial. The use of Windows Installer on our device may cause the device to become brick, so it needs to be installed manually by dism/dism++

Steps: Use DISM++ to install Windows, Use DISM++ to install drivers, Do some things to disable driver signature verification, BOOT IN
Result: Infinite loading **OF WINDOWS**

**Comment by Idonotkno** [comment]
@RusJJ Wrong boot or uefi image

**Comment by RusJJ** [comment]
> @RusJJ Wrong boot or uefi image

Wrong Boot image? wat
Wrong UEFI won't let me even load into the OS.

**Comment by Idonotkno** [comment]
@RusJJ efi or uefi boot

**Comment by RusJJ** [comment]
Old Windows. Fixed with the latest Windows 11 (for example)
