### ISSUE TITLE
Driver Audio SDM845 for Windows Arm

### ISSUE THREAD

**Issue by SangkarJanda** [edk2-porting/WOA-Drivers#98]
Is Renegade-Project still running or what is this? The last driver update will be in October 2022. The problem is that there are still many devices that have not been resolved. Driver problems, especially audio drivers, are very important. If the audio driver can be completed then this project can be said to be a success. It's only halfway there now, and there's been no word at all about an update to fix this issue. It's a shame that things have gone this far 😔😔😔

**Comment by SangkarJanda** [comment]
No response, from everyone.

**Comment by qaz6750** [comment]
Please note that most of the equipment in this project is currently not actively maintained by anyone, and I think that the built-in audio support for SDM845 may never come

**Comment by SangkarJanda** [comment]
> Please note that most of the equipment in this project is currently not actively maintained by anyone, and I think that the built-in audio support for SDM845 may never come

No wonder there hasn't been a new update for 1 year, it turns out the Renegade project is dead.

**Comment by Naletury** [comment]
i think u could try [AudioRelay](https://audiorelay.net), bluetooth connected to ur headphones or to buy a usb driverless soundbar
